version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    volumes:
      - uploads:/app/uploads

  mongo:
    image: mongo:8.0
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  uploads: